
// This file has been generated by the GUI designer. Do not modify.
namespace KeyKeeper
{
	public partial class ActionDlg
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label labelName;
		private global::Gtk.Table table1;
		private global::Gtk.Button button11;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label label2;
		private global::Gtk.Label label3;
		private global::Gtk.Button button12;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Label label4;
		private global::Gtk.Label label5;
		private global::Gtk.Button button3;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget KeyKeeper.ActionDlg
			this.Name = "KeyKeeper.ActionDlg";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child KeyKeeper.ActionDlg.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.labelName = new global::Gtk.Label ();
			this.labelName.Name = "labelName";
			this.labelName.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.vbox2.Add (this.labelName);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.labelName]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.button11 = new global::Gtk.Button ();
			this.button11.CanFocus = true;
			this.button11.Name = "button11";
			// Container child button11.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.HeightRequest = 15;
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("1");
			this.vbox3.Add (this.label2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label2]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Приход\nна работу");
			this.label3.Justify = ((global::Gtk.Justification)(2));
			this.label3.Selectable = true;
			this.vbox3.Add (this.label3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label3]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.button11.Add (this.vbox3);
			this.button11.Label = null;
			this.table1.Add (this.button11);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.button11]));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button12 = new global::Gtk.Button ();
			this.button12.CanFocus = true;
			this.button12.Name = "button12";
			// Container child button12.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.HeightRequest = 15;
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("1");
			this.vbox4.Add (this.label4);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label4]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Уход\n с работы");
			this.label5.Justify = ((global::Gtk.Justification)(2));
			this.label5.Selectable = true;
			this.vbox4.Add (this.label5);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label5]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.button12.Add (this.vbox4);
			this.button12.Label = null;
			this.table1.Add (this.button12);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.button12]));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add (this.table1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table1]));
			w11.Position = 1;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w12.Position = 0;
			// Internal child KeyKeeper.ActionDlg.ActionArea
			global::Gtk.HButtonBox w13 = this.ActionArea;
			w13.Name = "__gtksharp_70_Stetic_TopLevelDialog_ActionArea";
			// Container child __gtksharp_70_Stetic_TopLevelDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.button3 = new global::Gtk.Button ();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString ("0 - Отмена");
			this.AddActionWidget (this.button3, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w13 [this.button3]));
			w14.Expand = false;
			w14.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 172;
			this.DefaultHeight = 309;
			this.Show ();
			this.button11.Clicked += new global::System.EventHandler (this.OnButton11Clicked);
			this.button3.Clicked += new global::System.EventHandler (this.OnButton3Clicked);
		}
	}
}
