
// This file has been generated by the GUI designer. Do not modify.
namespace KeyKeeper
{
	public partial class SearchEntry
	{
		private global::Gtk.HBox hbox1;
		private global::Gtk.Image image6;
		private global::Gtk.Entry entry1;
		private global::Gtk.Button button27;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget KeyKeeper.SearchEntry
			global::Stetic.BinContainer.Attach (this);
			this.Name = "KeyKeeper.SearchEntry";
			// Container child KeyKeeper.SearchEntry.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.image6 = new global::Gtk.Image ();
			this.image6.Name = "image6";
			this.image6.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-find", global::Gtk.IconSize.Menu);
			this.hbox1.Add (this.image6);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image6]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '•';
			this.hbox1.Add (this.entry1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entry1]));
			w2.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button27 = new global::Gtk.Button ();
			this.button27.CanFocus = true;
			this.button27.Name = "button27";
			this.button27.UseUnderline = true;
			// Container child button27.Gtk.Container+ContainerChild
			global::Gtk.Alignment w3 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w4 = new global::Gtk.HBox ();
			w4.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-remove", global::Gtk.IconSize.Menu);
			w4.Add (w5);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w7 = new global::Gtk.Label ();
			w7.LabelProp = global::Mono.Unix.Catalog.GetString ("_Очистить");
			w7.UseUnderline = true;
			w4.Add (w7);
			w3.Add (w4);
			this.button27.Add (w3);
			this.hbox1.Add (this.button27);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button27]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.entry1.Changed += new global::System.EventHandler (this.OnEntry1Changed);
			this.entry1.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnEntry1FocusOutEvent);
			this.entry1.FocusInEvent += new global::Gtk.FocusInEventHandler (this.OnEntry1FocusInEvent);
			this.button27.Clicked += new global::System.EventHandler (this.OnClearEntry);
		}
	}
}
